### ISSUE TITLE
My neighborhood ux - mobile designs

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1093]
work with GA team 
and help develop 
- wire frames 
- design elements 
- user flow

**Comment by carolinestj** [comment]
*GA desktop*
https://projects.invisionapp.com/share/ACQNBUPXBUQ#/screens

*GA Mobile* 
https://projects.invisionapp.com/share/KNQJC2LCUZP#/screens/346928570

*My version*
https://xd.adobe.com/view/827b32b5-ef6c-4bfe-6c4f-e554825a5605-f44a/

**Comment by paylakatel** [comment]
Things to think about and get designs for:

- Selecting an address user flow - because of the geocoder we're using we need to use the same flow [311](https://311-uat.digital-staging.boston.gov/) does where a user enters an address and selects the one they want from the list.
- Error states - what do we do when we can't find an address a user selected (can/should be similar to what we do for 311 for consistency across apps).
- Text inside each card/drop down - [this spreadsheet](https://docs.google.com/spreadsheets/d/1g4hNd-15WTy_hbSKb7Di1XzfCQsCBatXxsg8-yTBgYY/edit?usp=sharing) has proposed datasets for each card
- Finalizing desktop designs

**Comment by carolinestj** [comment]
- Remove art and landmarks 
- remover food resources but think about if we can add it anywhere else
Kayla's suggestion: maybe fresh trucks in winter / farmers market summer 
- take out the blue headlines and swap for dark blue 
- Think about hierarchy maybe some words should be bold etc 
- think about language: your library, nearest library etc 
- maybe have the search bar following
