### ISSUE TITLE
Boston saves JCD ad 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#1459]
Contact: Katie Liesener

- Create digital ads for boston saves 
- digital screens around city hall

**Comment by sebastianebarb** [comment]
Hi guys, sorry for the late feedback - I was wrapping up last-minute portal tasks before leaving for North Carolina. Anyway, Sebastian, feel free to run with the feedback below. Otherwise, I think it's ok to wait til Caroline gets back. And thanks to both of you for your help!
The call-out text at the top has to identify BPS kindergarten families (or something to that effect). This ad only pertains to them, so we want to get their attention immediately.
The body text has to indicate that the $50 is for "their future" (or "college or career training"). 
The call to action at the end has to include the word "log in" - that's the newly available action that we're trying to get families to take.
For any of the above, see the original copy (below), if that helps.
Visually, we'd really like to have an image of a kindergarten-age child, if possible. Even better if it suggests their dreams of what they might want to be when they grow up. (I have photos of Boston Saves kids I can share, if that's helpful. Just let me know.) 
Thanks!
Katie
