### ISSUE TITLE
Review Upaknee templates for City of Boston brand consistency

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/design-team-workflow#2295]
Upaknee, the City of Boston's newsletter software, recently added new templates to the system. Previous templates had been within the City of Boston's brands, and these new ones look close, but we want @carolinestj to confirm that.

Caroline, you should see an email from "Campaign Manager" with details on accessing the system. To make things easier, we set up a dummy campaign. [You can preview all of the existing templates here](https://boston.upaknee.com/ui/campaigns/13261926/edit/step3).

We're looking to confirm that:

- [ ] These new templates fit / match the City of Boston's brand
- [ ] The templates are also ADA accessible

There's no deadline or timeline for this request. If you can pick this up in the next few weeks, that would be great.

**Comment by carolinestj** [comment]
@duffy-james 
can we remove this logo at the bottom? Since we have the logo at the top I think we don't need it at the bottom. 
Is it possible to make the headlines be uppercase? 
![Screen Shot 2022-06-17 at 09.54.13.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/9ed12521-25b5-4be4-a09e-c5c5a0845bae)


the grey on grey text fails ADA requirements, the text should be changed to the normal black/charles river blue 

![Screen Shot 2022-06-17 at 09.55.33.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/e39c24eb-49a6-41e5-9a35-d5a59d5170db)

Grey headline doesn't pass ADA requirement, the text should be changed to the normal black/charles river blue 
![Screen Shot 2022-06-17 at 10.12.14.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/ceaf5ae8-be3a-4035-bd90-ed3d301748b5)

Text shouldn't be centered, but left aligned for readability, grey text  doesn't pass ADA requirement, the text should be changed to the normal black/charles river blue 
![Screen Shot 2022-06-17 at 10.17.38.png](https://images.zenhubusercontent.com/5ca279ab45147541ad68a704/3e0eb28a-ccea-49df-88dd-73ac429c3af1)
