### ISSUE TITLE
Boston Food Access booklet

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#353]
Hi Sebastian,
I hope you are doing well. The Office of Food Initiative is working in release a Boston Food Access booklet.  We also are planning to create one page (in some cases two pages) sheets with neighborhood specific information. This material will be a food access resource for our constituents and will be distributed in several locations across the city. We would like that this booklet comply with the City of Boston brand guidelines. I am wondering if you can help us with the design.

We are very close to finishing putting together all the information and we would like to send this to be printed no later than the second week of June.

I am including Elizabeth Miller, my colleague here at the OFI in this e-mail. Liz is leading this project in partnership with BPHC and she would be happy to talk in more detail with you.

Attached is an example of what we envision the flyer will look like.

Have a wonderful weekend!

Catalina

**Comment by carolinestj** [comment]
[Dorchester CHC Resources_Revised_051617.docx](https://github.com/CityOfBoston/design-team-workflow/files/1032242/Dorchester.CHC.Resources_Revised_051617.docx)

**Comment by sebastianebarb** [comment]
Hi Sebastian and Caroline,

Attached is the full resource list. It still needs to be cleaned up a bit. There are some items that are repeated where they shouldn't be so this is slightly longer than it will be in its final version, and we may find ways to combine or simplify, but I wanted to share now to give you a sense of what we're working with. I will work on cleaning this up for the rest of this week. Please let me know if you have any questions or concerns about this. 

Catalina and I will also discuss the quote further tomorrow or Thursday and get a final decision to you by Friday at the latest if we can. Will that give us enough time to get an invoice before June 16th (next Friday)?

Also, regarding the map, the reason I couldn't remember what BPDA said about that is because they actually didn't get back to me on it. But I have a meeting with them on Tuesday so I will ask about it then. Since we aren't as rushed on our design, I assume that is fine...? For now, the link to the map is below so that you can see what they did. If you have any specific requests of them after looking at this, please let me know. This map includes much more information than will be going on the printed resource map. It's really just the stuff on the "Food Resources" tab that is related to this project.  

https://boston.maps.arcgis.com/apps/MapSeries/index.html?appid=327116a761dc4ef894962b6c237f7394

Thanks to you both for all your help!

**Comment by carolinestj** [comment]
[Full Food Resource List.docx](https://github.com/CityOfBoston/design-team-workflow/files/1058161/Full.Food.Resource.List.docx)

**Comment by carolinestj** [comment]
Some feedback: 

Make sure the colors are colorblind accessible, if not maybe try and change to symbols instead? 
Maybe try and add the neighborhood names back in?
Street names?

**Comment by carolinestj** [comment]
Notes from meeting

Tasks for Elizabeth: 

– Get abbreviated terms for weekdays & months  
– Get additional translation for 'Map of Boston', 'Updated' and 'Food resource list and map'
– talk to James and Reilly about setting up webiste

Sebastian & Caroline
– add language signifier on cover 
– Add website link
