### ISSUE TITLE
Summer Events (multi)

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#393]
August 6 - GospelFest
September 14 - Country in the City
September 16 - Boston Social Fitness Festival
September 17 - Hub on Wheels

**Comment by sebastianebarb** [comment]
[MAYORWALSHANNOUNCESSUMMER2017EVENTSLINEUP.pdf](https://github.com/CityOfBoston/design-team-workflow/files/1105569/MAYORWALSHANNOUNCESSUMMER2017EVENTSLINEUP.pdf)

**Comment by reneebarouxis** [comment]
Finally joined github. Thanks, @sebastianebarb & @carolinestj.

**Comment by sebastianebarb** [comment]
@reneebarouxis do you have dimensions?

**Comment by sebastianebarb** [comment]
![country in the city](https://user-images.githubusercontent.com/20642299/27708736-d2b81a46-5ce7-11e7-9f92-e6aa156c4585.png)
![summer concert-01](https://user-images.githubusercontent.com/20642299/27708589-7389fbde-5ce7-11e7-8f46-d68115c97afa.png)

![fitness festival-01](https://user-images.githubusercontent.com/20642299/27708590-73ab0374-5ce7-11e7-9220-a2087bb39f78.png)

**Comment by carolinestj** [comment]
![hubonwheels-04](https://user-images.githubusercontent.com/22770827/28167932-62241158-67ab-11e7-8a47-432cfdd438db.png)

**Comment by reneebarouxis** [comment]
@carolinestj thanks for adding hub in wheels! looks great!

**Comment by reneebarouxis** [comment]
@carolinestj p.s. here is last year's gospelfest poster for reference. if possible, i'd like to keep the brand's yellow as the main color.

![gospelfest copy](https://user-images.githubusercontent.com/29733592/28169601-e0ca40a4-67b0-11e7-9ba1-9b299105ceb2.jpg)

**Comment by reneebarouxis** [comment]
@carolinestj as for the fitness festival, i can't find any of quin's work. this might help us refine that design a bit. it would be nice to incorporate more "fun exercise," e.g. rock wall climbing, zumba class, the "dance mile." i found this website for last year's event: http://socialfitnessfestival.com/. here are a few pictures too.

![img_3462 copy 2](https://user-images.githubusercontent.com/29733592/28169894-b3a57dfe-67b1-11e7-81c3-48a979998893.JPG)
![unnamed-5 copy](https://user-images.githubusercontent.com/29733592/28169964-e3dcc00e-67b1-11e7-9378-edb8c108d54c.jpg)
![unnamed-1 copy](https://user-images.githubusercontent.com/29733592/28169963-e3d87972-67b1-11e7-9f8f-457c51cf6b4a.jpg)

**Comment by reneebarouxis** [comment]
@carolinestj @sebastianebarb Finally got a little clarity on the Social Fitness Festival & Hub on Wheels.

The City consults with Jim Delaney (I think https://www.linkedin.com/in/jimdelaney/) and Shelby Thompson (I think https://www.linkedin.com/in/shelbyreedthompson/) for marketing these two events. I'm getting introduced next week. Let's talk about how to steer their design work this afternoon. I love your work on Hub on Wheels.

Sorry this wasn't brought to our attention sooner :/

Going forward, the three of us should focus on Gospelfest 2017 and Country in the City 2017. Then, when there is time, we can loop back to the Friday Afternoon Concert Series, Caliente, and Celebration of Summer IV: Donna Summer Roller Disco Party for 2018.

**Comment by reneebarouxis** [comment]
@sebastianebarb @carolinestj The performance should be listed as by Anthony Brown & group therAPy. Please note the stylization here. That being said, I think it would be better to use a shot of just Anthony Brown rather than a group shot. Thanks!

![anthony-287](https://user-images.githubusercontent.com/29733592/28182636-d28420da-67da-11e7-91e6-83ed0b6db8f6.jpg)
![anthony-287bw](https://user-images.githubusercontent.com/29733592/28182642-d28f8ee8-67da-11e7-8a60-0704adc472cb.jpg)
![anthonybrown no effects copy](https://user-images.githubusercontent.com/29733592/28182638-d285e2f8-67da-11e7-83f0-50b245e38865.jpg)
![group therapy copy](https://user-images.githubusercontent.com/29733592/28182639-d2871588-67da-11e7-9db5-07d72106607f.jpg)
![photo 1](https://user-images.githubusercontent.com/29733592/28182635-d283e340-67da-11e7-8386-02ea21818301.jpg)
![photo 2](https://user-images.githubusercontent.com/29733592/28182637-d28452e4-67da-11e7-9de0-b42a010cc36a.jpg)
![photo 4](https://user-images.githubusercontent.com/29733592/28182640-d28e5dde-67da-11e7-8914-b8e428e8cc63.jpg)
![rtccimg_0593anthonybrownrcadiz copy](https://user-images.githubusercontent.com/29733592/28182641-d28f8e02-67da-11e7-99c7-355df51e1ec7.jpg)
![cover](https://user-images.githubusercontent.com/29733592/28182643-d290213c-67da-11e7-85f3-de91364a800f.jpg)
![rtccimg_0781anthonybrownrcadiz](https://user-images.githubusercontent.com/29733592/28182645-d2963e3c-67da-11e7-9aa4-3c3c14080779.jpg)
![trustinyou](https://user-images.githubusercontent.com/29733592/28182644-d292a240-67da-11e7-9ab8-c5ca430e34f7.jpg)
![anthony-125-2](https://user-images.githubusercontent.com/29733592/28182656-d76daa80-67da-11e7-8054-5ffc6e1e2231.jpg)
![anthony_0641](https://user-images.githubusercontent.com/29733592/28182660-d76f7f04-67da-11e7-9907-bcffbcfc3f40.jpg)
![anthony_0621grey](https://user-images.githubusercontent.com/29733592/28182657-d76e4ec2-67da-11e7-824a-445616a0fa51.jpg)
![anthony_0583grey](https://user-images.githubusercontent.com/29733592/28182658-d76ec8d4-67da-11e7-80dd-9d9f286f9523.jpg)
![anthony_0583](https://user-images.githubusercontent.com/29733592/28182661-d76fd6fc-67da-11e7-9b63-3e89b7ad1eb0.jpg)
![ajbcover 2 copy](https://user-images.githubusercontent.com/29733592/28182659-d76f66fe-67da-11e7-973f-826262cf1dd6.jpg)
![736c8281](https://user-images.githubusercontent.com/29733592/28182663-d7830bb4-67da-11e7-943a-c13f88c81725.jpg)
![unnamed-2](https://user-images.githubusercontent.com/29733592/28182662-d7825462-67da-11e7-9bb0-f006e48b2a39.jpg)
![unnamed-1](https://user-images.githubusercontent.com/29733592/28182665-d78cb664-67da-11e7-8bef-7e933c61b735.jpg)
![unnamed](https://user-images.githubusercontent.com/29733592/28182664-d786143a-67da-11e7-8faf-b8908089ec8c.jpg)
