### ISSUE TITLE
How to video interesting links

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#452]

**Comment by sebastianebarb** [comment]
![screenshot 2017-09-12 10 06 12](https://user-images.githubusercontent.com/20642299/30330518-4cfc39f4-97a3-11e7-9fcd-50c0fc93b4cf.png)
https://vimeo.com/91496760
https://vimeo.com/ondemand/moodboard/128388824
https://vimeo.com/41800652
![Screenshot 2017-09-12 10.20.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c364167e3e7856e37a20cbb178f1112943434d0eee1e020a17b8eb8339a3b16f708d595eead4655d21c66813adb8804eea05bc73825d99a4fedb1294b7607caddecd5d340c041f83fe5835a59b49ce5bf44be14f51b65e.png)

**Comment by carolinestj** [comment]
http://videos.homedepot.com/detail/videos/appliances/video/5432046876001/how-to-clean-an-oven?autoStart=true
https://www.vox.com/videos

**Comment by DACole** [comment]
to many links....
I can add some screen grabs when I get back.

http://motionographer.com/quickie/bill-clinton-s-north-korea-negotiator-has-advice-for-trump-
hbo/
<img width="1247" alt="screen shot 2017-09-12 at 3 49 41 pm" src="https://user-images.githubusercontent.com/25957670/30345364-cd7e617c-97d2-11e7-8a0f-f3e3672f6c0b.png">



http://motionographer.com/quickie/ash-to-art-animation/

<img width="1190" alt="screen shot 2017-09-12 at 3 50 16 pm" src="https://user-images.githubusercontent.com/25957670/30345378-dbfb0778-97d2-11e7-801e-0c5644545318.png">


http://motionographer.com/quickie/disillusionment-of-10-point-font/
<img width="1203" alt="screen shot 2017-09-12 at 3 50 42 pm" src="https://user-images.githubusercontent.com/25957670/30345387-e171ccfa-97d2-11e7-8eb3-f38d2a7c09f9.png">


https://www.youtube.com/watch?v=dp3NK7TMMzw
<img width="1108" alt="screen shot 2017-09-12 at 3 51 13 pm" src="https://user-images.githubusercontent.com/25957670/30345395-e8d73638-97d2-11e7-8ed8-741a6415eb16.png">

https://mymotiv.com/?gclid=CjwKEAiA17LDBRDElqOGq8vR7m8SJAA1AC0_Nal6O0xKwnoXFTuB9uIo3_DMtML5NZfuz9nH2kxi_BoCkZjw_wcB
<img width="1508" alt="screen shot 2017-09-12 at 3 51 27 pm" src="https://user-images.githubusercontent.com/25957670/30345401-ee9a189c-97d2-11e7-9122-3ecd50acf066.png">


https://www.youtube.com/watch?v=0NLZsEfnNrw
<img width="1107" alt="screen shot 2017-09-12 at 3 52 09 pm" src="https://user-images.githubusercontent.com/25957670/30345411-f4bf1560-97d2-11e7-82f7-c0ce28e58ef9.png">

https://www.youtube.com/watch?v=02GeyzIeBJw
<img width="1092" alt="screen shot 2017-09-12 at 3 52 31 pm" src="https://user-images.githubusercontent.com/25957670/30345423-faeb1de4-97d2-11e7-9f9a-6c2ee3847970.png">

https://www.youtube.com/watch?v=sLu5AIwuUEg
<img width="1116" alt="screen shot 2017-09-12 at 3 53 00 pm" src="https://user-images.githubusercontent.com/25957670/30345434-081e5b34-97d3-11e7-8c9e-c9f76fa42ba9.png">

**Comment by DACole** [comment]
I was watching the home depot videos and noticed they are using a few different techniques over the course of their catalog. The new graphics we watch seems to be their most updated style guide..

Would we be employing a similar technique. Design changes are current with continued production?

**Comment by DACole** [comment]
The idea of mixed media from the mood boards video is one we have been doing a bit informally, having sections of a video be different from one another. This guideline is going to be a framework for how to think about the process of creating a how to video more so that this is how to make one...

 best practices vary depending on resources, time, and creativity of the design. Though all of these examples work very well.

1. 
The "how to video" should visually indicate each step of the process. This allows for the viewer to mentally orient themselves within the tutorial. 

2.
Voice-over or a on camera host should be present in most cases unless type or a visual direction proves to be stronger. 

3. 
Provide direction through on screen graphics. Properly formatted typography can be support for the voice over.

4. 
Consult an export to make sure facts are clear and up to date about how to properly execute the process. 

5.
Video should end with current brand graphic or motion graphic build.  


I am going to give this another go....
