### ISSUE TITLE
BPS performance meter

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/design-team-workflow#685]
Start date: april 17 2018 
Contact: Jacob Stern jstern2@bostonpublicschools.org

We are building a 'Performance Meter' in tableau that will be a high level public facing report on Boston Public Schools' performance and we would appreciate some support on the design to make it look professional and clear to all audiences.

**Comment by sebastianebarb** [comment]
Hi Sebastian,

Thanks for taking the time to talk with me and Jake last Friday. Like we talked about, I'm sharing some links and additional context -- any feedback you have would be great. These are certainly still a work-in-progress, and while uploaded to Tableau Public, not really public yet, so please don't share the links.

Landing page (iterations one, two and three)
- The goal of this page is to provide a high-level view of the 14 metrics. Stakeholders would like to be able to see current data, the 1 and 5 year targets, and how the data has changed from the previous year.
- Of the 14 metrics, 8 are key times in the K-12 trajectory of students. The other 6 are what we're calling "supporting metrics". Those 6 are not included in iteration 3 currently. One of the challenges is that one of the supporting metrics (suspension rate) is a metric that we want to see decrease. All of the other metrics we want to see increase.
- There's also an interest around visualizing achievement gaps. Iteration 3 does that by displaying the number of the gap size between specific subgroups. This section feels like the least intuitive part, and I am toying with the idea that it should be on a separate drill-down tab.
- Iteration one shows the gauges that have received positive feedback from leadership, but we've struggled to re-create in Tableau.

Metric drilldowns (link)
- For each metric, we'd like the user to be able to drill into historical performance. The important sections to include here are performance for all students for 4 years, plus the 1 and 5 year targets. Additionally, it's important to be able to disaggregate historical performance by different subgroups in order to visualize achievement gaps.
- There have been minimal changes to these templates, but I'm having trouble with the white space and sizing.

Let me know if you need any additional context, and what feedback you have about how to move forward.

Thanks!
Monica

**Comment by sebastianebarb** [comment]
[BPS performance meter.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46caa4a9639286bb89e6ad4ea553f391694b22672c16e1673295f127b54778154d555ca9460b5f43f9ac8e2eaeb46970df5e0aedd33c0a70c06e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8d4b3c1d011a8afd5c33a78b06.pdf)
