### ISSUE TITLE
Early voting

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#765]
2018 EARLY VOTING PLANNING MEETING MINUTES
DATE:
​06/19/2018
ATTENDANCE:
Dion Irish
Jeanethe Falvey
Ky’ron Owens
Sabino Piemonte
Sam Ormsby
Sebastian Ebarb
Timothy Sullivan
DEPARTMENT TASKS:
Boston Election Department
● Handle printing & translation of all outreach materials
● Get design files from MORE Advertising
● Provide the final EV schedule following board approval
● Give a Sebastian a list of all collateral
● List out Press Release topics and send over to Sam
● Look into promotional opportunities through Bike System
● handle newspaper advertising “buys”.
Department of Innovation and Technology
● Design materials for print
● Look into if Facebook can send an alert to people in Boston
● Create graphics for Early Voting – short lines, open locations, etc.
● Assist with the purchase of paid ads on facebook & twitter
● Early Voting Webpage edits, Create Site Alert, Create Events in Event Calendar, and
Update Neighborhood Pages
Mayor’s Press Office
● Assist with generating free coverage in neighborhood newspapers
● Help with planning TV interviews
● Assist with drafting Press Releases
● Assist with Mayor’s Column and placement in Neighborhood Papers
Intergovernmental Relations
● Contact Secretary of State to find plans for promoting Early Voting
● Contact MBTA to find out if as a government agency do we get a discount or free
placement on the Digital advertising or advertising on the trains.
NEXT MEETING IS JULY 11, 2018

**Comment by carolinestj** [comment]
[Early Voting Outreach Materials List.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57fcece44095e71300552840/125516c66e82c728ace21e0d46cd95882f9bc39f80fdb64da31ddf813d5422722a0ce3067191e63ab64377124f2317ef054a4356bcbbd671f3e57862804e0eea826d5871933a14a4bad71fea03bb20891ed0b2bad945d2f42f67b6d5db1063474f4dcbed5727a19141c95df54be94557ac153167e0722431.pdf)

**Comment by sebastianebarb** [comment]
[2018 EV Schedule - Final.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/579a426a8f594a13008422a3/125516c66e82c728ace21e0d46bac4cb7bc2a69fcfdabc4ba159e5982c066a330f0dad2a7cc7af6aaf50740b0a0c0abe4b4a5a43aff98e2ef3b1397888090bb8d36c5f76976815aaeb8b0da313f871d51bdaebe5c01982fa3737e68c854e3b1d041b8dfe5b3ca19f42c04abb.pdf)

**Comment by sebastianebarb** [comment]
Diana Laird

Status: 
 3 English files done;  Flyer, 11x17 Poster, 18x24 Poster
All three pdf proofs are with Ky'ron Owens

The folder is already shared with you but just in case here is the link
https://drive.google.com/drive/folders/1R_d75IsypZmA-iKbii0ddB3VGcnGNq_A?usp=sharing

**Comment by carolinestj** [comment]
Meeting notes august 24 
Flyer: 
- update zip codes 

Bus ad: 
- remove last middle paragraph  and voter status

News paper ad: 
- add formerly know as back in 
- remove ( - ) add neighborhood 

Polling signs 
- remove last middle paragraph and voter status 
- city hall: dates for entire run, M,W & F 9-5, Tu & Th 9-8 

Mailer: 
- zip code 
- update map

**Comment by carolinestj** [comment]
https://mail.google.com/mail/u/0/?zx=gzvt9etsalky#inbox/FMfcgxvzKkmXvFxblXFRwxqnFqVSQhZC?projector=1&messagePartId=0.1
Can you please review the newspaper ads and adjust them to the specs specific for each paper identified in the spreadsheet attached. Once you have fit the ads to size please send over the design files and pdf versions similar to last time however, can you please separate and label them by newspaper instead of sending them all as one file in the folder?

Can you please update the location for the Perkins Community Center/ Joseph Lee School from the Auditorium to the Gymnasium in each of the Early Voting Flyers and any where else we list it in other materials. Once complete can you please send me the updated design files. I have sent all of the current design files to your via google links in this email.
