### ISSUE TITLE
Rebrand video: Age Strong

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/design-team-workflow#993]
Contact: cassandra.baptista@boston.gov
Due: Nov- Dec

https://waffle.io/CityOfBoston/design-team-workflow/cards/5b7ed074b7ee7a001bc04ad5

The Elderly Commission will be rebranding themselves in the next few months they will need an ad to explain what they do. Set up edits for broadcast, social and the city's website. 30 second video, keying off of the new brand.

**Comment by KristinaVicario** [comment]
Here are the details that Kris Carter sent me regarding a very rough draft script for this project: 
Video announcing the new name
30 second, 60 second spot to air on Comcast, BNN, and Boston City TV
All B-roll should be empowering shots of older adults.

Videos shots/Script
 
In Boston, our strength comes in many forms. We have:

Strong culture (parades, different ethnic communities, north end festivals, Chinese Golden Age)
Strong relationships (b-roll of Mayor Walsh hugging a senior)
Strong weather (snow. wind)
Strong history (Freedom trail)
Strong dance moves (dance moves from one of our parties)
Strong voices and opinions (civic academy, seniors testifying at things, )
Strong community (people holding hands, older and bolder group)
Strong leaders (seniors speaking up, Mayor Walsh with older adults)
 
That’s why we’re done with labels, like elderly. Because they don’t tell our story. Instead we’re focused on how we can embrace aging (show a hug maybe between a senior and Commissioner Shea) and do it well together (Mayor holding hands with a senior).  

As a Commission, we’re not new to aging. We’ve been doing it for 50 years. See how all of our experiences make up our strengths at the new Age Strong Commission. Age with us. 

Because in Boston, we Age Strong.

**Comment by KristinaVicario** [comment]
Going through footage with Dave Burt once he finishes uploading it into G-drive.

**Comment by KristinaVicario** [comment]
Attending two events the week of the 8th to gather new, relevant b-roll of Age Strong folks at events.

**Comment by KristinaVicario** [comment]
4/19
Received b-roll from cable - only able to download one clip - Phil coming in later today to see if he can assist. 
Going out to Codman Square Library to shoot addition b-roll of age strong folks.

**Comment by KristinaVicario** [comment]
Age Strong Outstanding Needs to finish brand video as we await for photographer for campaign video 

- Age Strong Staff Helping 
-Strong Weather
-Strong History (shots of the freedom trail)
-Mayor with Seniors (at neighborhood coffee hour)
-Elders taking the shuttle
